# Generated by Django 5.1.7 on 2025-04-05 17:29

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['room_number']},
        ),
        migrations.AlterModelOptions(
            name='roommatepreference',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='date_booked',
            new_name='booking_date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='occupied',
        ),
        migrations.RemoveField(
            model_name='roommatepreference',
            name='preferences',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 5, 17, 29, 8, 876228, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='booking',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.booking'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('QR', 'QR Code'), ('Manual', 'Manual Payment')], default='Manual', max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.TextField(blank=True, help_text='Comma-separated list of amenities'),
        ),
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='last_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('triple', 'Triple Room')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='roommatepreference',
            name='additional_preferences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roommatepreference',
            name='cleanliness',
            field=models.CharField(choices=[('very_neat', 'Very Neat'), ('moderately_neat', 'Moderately Neat'), ('relaxed', 'Relaxed')], default='moderately_neat', max_length=20),
        ),
        migrations.AddField(
            model_name='roommatepreference',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='roommatepreference',
            name='interests',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='roommatepreference',
            name='study_habits',
            field=models.CharField(choices=[('early_bird', 'Early Bird'), ('night_owl', 'Night Owl'), ('flexible', 'Flexible')], default='flexible', max_length=20),
        ),
        migrations.AddField(
            model_name='roommatepreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
    ]
