# Generated by Django 5.1.7 on 2025-04-05 17:55

import django.db.models.deletion
import hostel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_alter_booking_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='has_ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_attached_bathroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_fridge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_wifi',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(default=hostel.models.get_default_checkout_date),
        ),
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=models.TextField(blank=True, help_text='Comma-separated list of additional amenities'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('standard', 'Standard Room'), ('deluxe', 'Deluxe Room'), ('luxury', 'Luxury Suite'), ('premium', 'Premium Suite')], default='standard', max_length=10),
        ),
        migrations.CreateModel(
            name='BookingPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_type', models.CharField(choices=[('days', 'Days'), ('months', 'Months'), ('year', 'Year')], default='months', max_length=10)),
                ('duration_value', models.IntegerField(default=1)),
                ('food_preference', models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('both', 'Both'), ('none', 'No Food Service Required')], default='none', max_length=10)),
                ('meal_plan', models.CharField(choices=[('breakfast', 'Breakfast Only'), ('breakfast_dinner', 'Breakfast and Dinner'), ('all_meals', 'All Meals'), ('none', 'No Meals')], default='none', max_length=20)),
                ('needs_parking', models.BooleanField(default=False)),
                ('needs_laundry', models.BooleanField(default=False)),
                ('needs_cleaning', models.BooleanField(default=False)),
                ('special_dietary_requirements', models.TextField(blank=True)),
                ('additional_requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hostel.booking')),
            ],
        ),
    ]
