# Generated by Django 4.2.20 on 2025-04-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_add_is_paid_field'),
        ('hostel', 'add_is_paid_field'),
        ('hostel', 'ensure_is_paid_field'),
    ]

    operations = [
    ]
