# Generated by Django 4.2.20 on 2025-04-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_merge_20250407_2230'),
        ('hostel', 'merge_migrations'),
    ]

    operations = [
    ]
