# Generated by Django 4.2.20 on 2025-04-28 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0004_merge_0003_merge_20250407_2230_merge_migrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingpreference',
            name='needs_parking',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingpreference',
            name='ac_preference',
            field=models.CharField(choices=[('required', 'AC Required'), ('preferred', 'AC Preferred but not mandatory'), ('not_required', 'AC Not Required')], default='preferred', max_length=15),
        ),
        migrations.AddField(
            model_name='bookingpreference',
            name='parking_type',
            field=models.CharField(choices=[('none', 'No Parking Required'), ('two_wheeler', 'Two-Wheeler Parking'), ('car', 'Car Parking'), ('both', 'Both Car and Two-Wheeler')], default='none', max_length=15),
        ),
        migrations.AddField(
            model_name='bookingpreference',
            name='preferred_roommate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roommate_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
